# Generated by Django 4.2 on 2023-04-22 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('image', models.ImageField(default='default.png', upload_to='categories/')),
                ('description', models.TextField(default='No description', max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('serial_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('details', models.TextField(max_length=1000)),
                ('image', models.ImageField(default='default.png', upload_to='equipment/')),
                ('is_available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.category')),
            ],
            options={
                'verbose_name_plural': 'Equipment',
            },
        ),
        migrations.CreateModel(
            name='IssueStatus',
            fields=[
                ('status', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Issue Status',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('full_name', models.CharField(max_length=100)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('room', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('details', models.TextField(max_length=1000)),
                ('image', models.ImageField(default='default.png', upload_to='studios/')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.equipment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.student')),
            ],
            options={
                'unique_together': {('student', 'item', 'date_from')},
            },
        ),
        migrations.CreateModel(
            name='IssueReport',
            fields=[
                ('date_opened', models.DateField()),
                ('date_closed', models.DateField(blank=True, default=None, null=True)),
                ('details', models.TextField(default='No details', max_length=1000, primary_key=True, serialize=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.equipment')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.issuestatus')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.student')),
            ],
            options={
                'unique_together': {('student', 'item', 'date_opened', 'date_closed', 'status')},
            },
        ),
    ]
