# Generated by Django 4.2 on 2023-05-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('B', 'Borrowed'), ('Q', 'In queue'), ('M', 'malfunction'), ('A', 'Available')], default=('A', 'Available'), max_length=100),
        ),
    ]
