# Generated by Django 4.2 on 2023-04-13 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_equipment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='default.png', upload_to='categories/'),
        ),
    ]
