<<<<<<< HEAD
# Generated by Django 4.2 on 2023-06-04 19:52
=======
# Generated by Django 4.2 on 2023-06-04 17:25
>>>>>>> 91a86ce6b5f2c3cdd5be524d480b9ee660ca27b3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_reservation_returned_alter_reservation_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
<<<<<<< HEAD
            field=models.CharField(choices=[('B', 'Borrowed'), ('Q', 'In queue'), ('M', 'malfunction'), ('A', 'Available'), ('W', 'Waiting'), ('P', 'Passed')], default=('A', 'Available'), max_length=100),
=======
            field=models.CharField(choices=[('B', 'Borrowed'), ('Q', 'In queue'), ('M', 'malfunction'), ('A', 'Available'), ('W', 'Waiting')], default=('A', 'Available'), max_length=100),
>>>>>>> 91a86ce6b5f2c3cdd5be524d480b9ee660ca27b3
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('student', 'item', 'date_from', 'status')},
        ),
    ]
