# Generated by Django 4.2 on 2023-04-13 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='No description', max_length=1000),
        ),
    ]
