# Generated by Django 4.2 on 2023-04-06 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_student_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='issuereport',
            unique_together={('item_serial_number', 'student_email', 'date_opened')},
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('student_email', 'student_id', 'item_serial_number')},
        ),
    ]
