# Generated by Django 4.2 on 2023-06-05 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_reservation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='time_from',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='reservation',
            name='time_to',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
