# Generated by Django 4.2 on 2023-04-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_category_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_from',
            field=models.DateField(primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='item_serial_number',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='student_email',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='student_id',
        ),
    ]
