# Generated by Django 4.2 on 2023-04-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_alter_issuereport_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuereport',
            name='id',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='id',
        ),
        migrations.AlterField(
            model_name='issuereport',
            name='item_serial_number',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='student_email',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
