# Generated by Django 4.2 on 2023-04-06 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_remove_issuereport_id_remove_reservation_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='issuereport',
            unique_together=set(),
        ),
    ]
