# Generated by Django 4.2 on 2023-04-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_reservation_item_reservation_student_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='issuereport',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='issuereport',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='issuereport',
            name='item_serial_number',
        ),
        migrations.RemoveField(
            model_name='issuereport',
            name='student_email',
        ),
    ]
