# Generated by Django 4.2 on 2023-04-14 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_alter_issuereport_unique_together_issuereport_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuereport',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.equipment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issuereport',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issuereport',
            name='date_opened',
            field=models.DateField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='issuereport',
            unique_together={('student', 'item', 'date_opened', 'date_closed')},
        ),
        migrations.RemoveField(
            model_name='issuereport',
            name='id',
        ),
    ]
