# Generated by Django 4.2 on 2023-04-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_alter_issuereport_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='image',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
    ]
