# Generated by Django 4.2 on 2023-04-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_equipment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='image',
            field=models.ImageField(default='default.png', upload_to='equipment/'),
        ),
    ]
