# Generated by Django 4.2 on 2023-04-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_issuereport_item_issuereport_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueStatus',
            fields=[
                ('status', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
