# Generated by Django 4.2 on 2023-04-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_alter_equipment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='details',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='issuereport',
            name='details',
            field=models.TextField(max_length=1000),
        ),
    ]
