# Generated by Django 4.2 on 2023-04-14 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_alter_issuereport_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuestatus',
            options={'verbose_name_plural': 'Issue Status'},
        ),
        migrations.AlterUniqueTogether(
            name='issuereport',
            unique_together={('student', 'item', 'date_opened', 'date_closed', 'status')},
        ),
    ]
