# Generated by Django 4.2 on 2023-04-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_alter_equipment_details_alter_issuereport_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('room', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('details', models.TextField(max_length=1000)),
                ('image', models.ImageField(default='default.png', upload_to='studios/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name_plural': 'Equipment'},
        ),
    ]
