# Generated by Django 4.2 on 2023-04-14 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_alter_issuestatus_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='issuereport',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='issuereport',
            name='date_opened',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='issuereport',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='database.issuestatus'),
        ),
    ]
