# Generated by Django 4.2 on 2023-04-14 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_alter_issuereport_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuereport',
            name='details',
            field=models.TextField(default='No details', max_length=1000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='issuereport',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.issuestatus'),
        ),
        migrations.AlterUniqueTogether(
            name='issuereport',
            unique_together={('student', 'item', 'date_opened', 'date_closed', 'status')},
        ),
    ]
