# Generated by Django 4.2 on 2023-04-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_alter_issuereport_details_alter_issuereport_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuereport',
            name='date_closed',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
