# Generated by Django 4.2 on 2023-04-15 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_alter_reservation_date_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='database.equipment'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.student'),
        ),
    ]
