# Generated by Django 4.2 on 2023-04-15 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_alter_reservation_item_alter_reservation_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.equipment'),
        ),
    ]
