# Generated by Django 4.2 on 2023-04-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_reservation_id_alter_reservation_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
