pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'python manage.py migrate' // Run database migrations
                sh 'python manage.py collectstatic --noinput' // Collect static files
            }
        }
        stage('Test') {
            steps {
                sh 'python manage.py test' // Run tests
            }
        }
        stage('Deploy') {
            steps {
                sh 'python manage.py makemigrations' // Create new migrations
                sh 'python manage.py migrate' // Apply new migrations
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully!' // Notify on success
        }
        failure {
            echo 'Pipeline failed!' // Notify on failure
        }
    }
}
